[package]
name = "kindmango"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
futures = "0.3.31"
reqwest = {version = "0.12.28",features = ["blocking"]}
serde = "1.0.228"
serde_json = "1.0.148"
tokio = {version = "1.49.0", features = ["full"]}
zip = "7.0.0"
